### PR TITLE
Add DICOM Stack data set

### PR DESCRIPTION
**Pull request by adam-grant-hendry**
See [PR #5](https://github.com/pyvista/vtk-data/pull/5) for original discussion (which was accidentally deleted).

This dataset will be used to test improved volume rendering and DICOM stack reading per [`pyvista/pyvista-support` issue #500](https://github.com/pyvista/pyvista-support/issues/500).

<p align="center">
    Skin Cancer  
</p>

The Cancer Imaging Archive (TCIA) is a service which de-identifies and hosts a large archive of medical images of cancer accessible for public download. The data are organized as “collections”; typically patients’ imaging related by a common disease (e.g. lung cancer), image modality or type (MRI, CT, digital histopathology, etc) or research focus. DICOM is the primary file format used by TCIA for radiology imaging. Supporting data related to the images such as patient outcomes, treatment details, genomics and expert analyses are also provided when available.

This dataset is a member of the National Cancer Institute's Clinical Proteomic Tumor Analysis Consortium Sarcomas (CPTAC-SAR) cohort. CPTAC is a national effort to accelerate the understanding of the molecular basis of cancer through the application of large-scale proteome and genome analysis, or proteogenomics. Radiology and pathology images from CPTAC patients are being collected and made publicly available by The Cancer Imaging Archive to enable researchers to investigate cancer phenotypes which may correlate to corresponding proteomic, genomic and clinical data.

This data has been published under the [Creative Commons Attribution 3.0 Unported License](http://creativecommons.org/licenses/by/3.0/) and must adhere to the [CPTAC Data Use Agreement](https://proteomics.cancer.gov/data-portal/about/data-use-agreement). Per the TCIA Data Usage Policy (see `License` file), all oral or written presentations, disclosures, or publications must acknowledge the specific dataset(s) or applicable accession number(s) and the NIH-designated data repositories through which the investigator accessed any data. The appropriate citations are included in the `Citations` file. The metadata for this dataset is included in `metadata.csv`. Questions may be directed to [help@cancerimagingarchive.net](mailto:help@cancerimagingarchive.net).

**Title:** Forearm Sarcoma
**DataDescription URI:** https://doi.org/10.7937/TCIA.2019.9bt23r95
**Number of Images:** 3
**Total Size:** 1.51 MB
**File Format:** DICOM

**Files:**  
[DICOM_Stack.zip](https://github.com/pyvista/vtk-data/files/8467437/DICOM_Stack.zip)
[LICENSE.txt](https://github.com/pyvista/vtk-data/files/8467424/LICENSE.txt)
[CITATION.txt](https://github.com/pyvista/vtk-data/files/8467508/CITATION.txt)
[metadata.csv](https://github.com/pyvista/vtk-data/files/8467505/metadata.csv)

### CODE REVIEW

**Comment by adam-grant-hendry** [comment]
@akaszynski @MatthewFlamm @banesullivan If you would, please review this PR at your earliest convenience. Once accepted, I will submit my PR to solve [issue #500](https://github.com/pyvista/pyvista-support/issues/500).

**Review by akaszynski — APPROVED** [review]
This is good to go. Thanks @adam-grant-hendry!

**Comment by MatthewFlamm** [comment]
This PR modified `Data/FORGE.omf`.  I'm not sure if that was intended.

**Comment by adam-grant-hendry** [comment]
@MatthewFlamm No, that was not intended. The reason PR #5 failed was because of a botched attempt to cherry-pick my commit on top of the latest master branch.

I noticed the commit message git wanted to commit was `Add forge data`, so I canceled that commit, deleted my branch, and manually recreated it on top of master since the change was simple.

What did this PR change?

**Comment by adam-grant-hendry** [comment]
@MatthewFlamm I see now. It appears `Data/FORGE.omf` was removed by @banesullivan in bd3721. IIRC, that was the base of my original branch, so perhaps I accidentally re-introduced the file.

I'll submit another PR to correct this.

**Comment by akaszynski** [comment]
I've removed `Data/FORGE.omf` in 72402e91a1ce8f150d6fa4b4cc13ad8cb3b2c2fe.

**Comment by adam-grant-hendry** [comment]
Thank you @akaszynski !

**Pull request merged**
